#! /usr/bin/env bash

set -eu

format_check="$(harness format --check &> /dev/null; echo "$?")"

# Check the format of the crystal code
if [[ "${format_check}" -eq 1 ]]
then
  echo '`harness format` produced changes.'
  echo 'Please run `harness format` before committing again.'
  exit 1
elif [[ "${format_check}" -eq 2 ]]
then
  echo 'Failed to connect to docker to run pre-commit checks.'
  echo 'Skipping pre-commit checks for now.'
  exit 0
fi
