Excluded:
  - repositories/**/*.cr

# NOTE: These should all be reviewed on an individual basis to see if their
#       complexity can be reasonably reduced.
Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
  - drivers/helvar/net.cr
  - drivers/mulesoft/booking_api.cr
  - drivers/samsung/displays/mdc_protocol.cr
  - drivers/cisco/dna_spaces.cr
  - drivers/cisco/meraki/dashboard.cr
  - drivers/cisco/switch/snooping_catalyst.cr
  - drivers/gantner/relaxx/protocol_json.cr
  - drivers/place/bookings.cr
  - drivers/place/area_management.cr
  - drivers/place/smtp.cr
  - drivers/hitachi/projector/cp_tw_series_basic.cr
  - drivers/panasonic/projector/nt_control.cr
  - drivers/lumens/dc193.cr
  Enabled: false
  Severity: Convention

Lint/UselessAssign:
  Description: Disallows useless variable assignments
  # NOTE: Not enabled due to the extremely large hit count.
  #       Discussion with driver authors on whether this pattern is intended.
  Enabled: false
  Severity: Warning

Style/VerboseBlock:
  Description: Identifies usage of collapsible single expression blocks.
  ExcludeCallsWithBlock: false
  ExcludeMultipleLineBlocks: true
  ExcludeOperators: false
  ExcludePrefixOperators: false
  ExcludeSetters: true
  Enabled: false
  Severity: Convention

Style/VariableNames:
  Description: Enforces variable names to be in underscored case
  # NOTE: Not enabled due to the extremely large hit count.
  #       Discussion with driver authors on whether this pattern is intended.
  Enabled: false
  Severity: Convention

# NOTE: These appear to be triggered by assignment in case expressions, could be an ameba bug
Lint/ShadowingOuterLocalVar:
  Description: Disallows the usage of the same name as outer local variables for block
    or proc arguments.
  Excluded:
  - drivers/cisco/switch/snooping_catalyst.cr
  Enabled: true
  Severity: Warning
