#! /usr/bin/env bash

# `e`: fail script if a command's exitcode is non-zero
# `u`: fail script if a variable is unset (unitialized)
set -eu

say_done() {
  printf "░░░ Done.\n"
}

fail() {
  echo "${@}" >&2
  exit 1
}

# Called when Ctrl-C is sent
function trap_ctrlc ()
{
  echo ">~"
  echo "░░░ Cleaning up..."
  down
  exit 2
}

trap "trap_ctrlc" 2

up() {
  echo '░░░ PlaceOS Driver Harness'
  echo '░░░ Starting environment...'
  docker-compose up -d &> /dev/null
  printf "░░░ The harness can be found at http://localhost:8085\n"
  echo '░░░ Stop the harness with `harness down`'
  say_done
}

down() {
  echo '░░░ Stopping PlaceOS Driver Harness...'
  docker-compose down --remove-orphans &> /dev/null
  say_done
}

format() {
  echo '░░░ Running `crystal tool format` over `drivers` and `repositories`'
  exit_code=0
  docker-compose run \
                     -v ./drivers:/wd/drivers \
                     -v ./repositories:/wd/repositories \
                     --no-deps \
                     --rm \
                     install-shards \
                     crystal tool format $@ || exit_code=$?
  say_done
  exit ${exit_code}
}

report() {
  echo '░░░ PlaceOS Driver Compilation Report'
  echo '░░░ Pulling images...'

  docker-compose pull &> /dev/null

  echo '░░░ Installing shards...'
  # Ensure shards are satisfied before running the report
  docker-compose run \
                     --rm \
                     install-shards # &> /dev/null
                     # --no-deps \

  echo '░░░ Starting environment...'
  docker-compose up -d &> /dev/null

  exit_code=0

  echo '░░░ Starting report...'
  docker exec placeos-drivers report $@ || exit_code=$?

  down
  exit ${exit_code}
}

usage() {
  cat <<EOF
Usage: harness [-h|--help] [command]

Helper script for interfacing with the PlaceOS Driver spec runner

Command:
    report                  check all drivers' compilation status
    up                      starts the harness
    down                    stops the harness
    format                  formats driver code
    help                    display this message
EOF
}

# Check the number of arguments passed.
if [[ "$#" -eq 0 ]]
then
  usage
  exit 1
fi

# Check if able to connect to docker
if [[ "$(docker ps &> /dev/null; echo $?)" -eq 1 ]]
then
  echo "░░░ Failed to connect to docker. Is it running?"
  exit 2
fi

command="$1"
shift
case $command in
  report)
    report $@
    ;;
  up)
    up
    ;;
  down)
    down
    ;;
  format)
    format $@
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    if [ -n "$command" ]; then
      fail "Unknown command: $command"
    else
      usage
      exit 1
    fi
    ;;
esac
