name: Deploy docs

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: "Install shards"
        run: shards install --skip-postinstall --skip-executables
      - name: "Generate docs"
        run: crystal docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
